---

- name: install unattended upgrades
  apt: update_cache=yes cache_valid_time=3600 pkg={{ item }} state=present # won't update if done under an hour ago
  with_items:
  - unattended-upgrades

- name: configure unattended upgrades settings
  template: src=etc/apt/apt.conf.d/50unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades

- name: configure unattended upgrades schedule
  template: src=etc/apt/apt.conf.d/10periodic.j2 dest=/etc/apt/apt.conf.d/10periodic
